// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/currency/date1/code": {
            "get": {
                "description": "Return list of currencies.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "currency1"
                ],
                "summary": "Get currency from DB.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Set date for currency",
                        "name": "date1",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Set code for currency",
                        "name": "code",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "obejct"
                        }
                    }
                }
            }
        },
        "/currencys/date1": {
            "get": {
                "description": "Return list of currencies.",
                "produces": [
                    "application/xml"
                ],
                "tags": [
                    "currency1"
                ],
                "summary": "Get All Currencirs from API.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Set date for currency",
                        "name": "date1",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "obejct"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4000",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Currency Service API",
	Description:      "A Currency service API in Go using Gin framework",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
