host: localhost:8080
info:
  contact: {}
  description: A Currency service API in Go using Gin framework
  title: Currency Service API
  version: "1.0"
paths:
  /currency/date1/code:
    get:
      description: Return list of currencies.
      parameters:
      - description: Set date for currency
        in: path
        name: date1
        required: true
        type: string
      - description: Set code for currency
        in: path
        name: code
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: obejct
      summary: Get currency from DB.
      tags:
      - currency1
  /currencys/date1:
    get:
      description: Return list of currencies.
      parameters:
      - description: Set date for currency
        in: path
        name: date1
        required: true
        type: string
      produces:
      - application/xml
      responses:
        "200":
          description: OK
          schema:
            type: obejct
      summary: Get All Currencirs from API.
      tags:
      - currency1
swagger: "2.0"
